version: '3'
services:
  database:
    image: postgres
    volumes:
      - ~/projects/demo/data:/var/lib/postgresql/data
    ports:
      - 5432:5432
  web:
    build: .
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://database:5432/postgres
    volumes:
      - ~/projects/demo:/usr/local/application-data
      - ~/.gradle/:/root/.gradle/
    ports:
      - 8080:8080
    links:
      - database