version: '3'
services:
  database:
    container_name: database
    image: postgres
    ports:
      - 5432:5432
  web:
    container_name: application
    build: .
    volumes:
      - ~/projects/demo:/usr/local/application-data
      - ~/.gradle/:/root/.gradle/
    ports:
      - 8080:8080
    links:
      - database